# Generated by Django 3.1.3 on 2020-11-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netgru_api_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make_name', 'model_name')},
        ),
    ]
